In [5]:
import pandas as pd
import numpy as np
import os

In [6]:
sims_df_fp = "../figs/ablation_exp/test_df.csv"
sims_latex_fp = "../figs/ablation_exp/test_df.tex"
sims_df = pd.read_csv(sims_df_fp)
display(sims_df)

,split_type,model_type,cos_sim_0.01_mean,cos_sim_0.01_std,cos_hun_mean,cos_hun_std,true_oos_prob_mean,true_oos_prob_std,pred_oos_prob_mean,pred_oos_prob_std,pearson_r_oos_mean,pearson_r_oos_std,tv_oos_mean,tv_oos_std
0,inchikey,fraggnn_d3_edges,0.715905,0.000795,0.687142,0.000584,0.171483,0.0,0.196112,0.005296,0.762090,0.003207,0.081143,0.001690
1,inchikey,fraggnn_d3_noce,0.711160,0.000642,0.682838,0.000800,0.171483,0.0,0.194856,0.004753,0.761192,0.004038,0.080412,0.001397
2,inchikey,fraggnn_d4_noce,0.721347,0.000510,0.694192,0.000613,0.097903,0.0,0.116629,0.008112,0.701032,0.007536,0.057318,0.003389

In [7]:
model_type_to_name = {
    "fraggnn_d3_noce": "FraGNNet-D3 (-CE)",
    "fraggnn_d3_edges": "FraGNNet-D3 (+Edges)",
    "fraggnn_d4_noce": "FraGNNet-D4 (-CE)",
    "fraggnn_d4_edges": "FraGNNet-D4 (+Edges)",
}

latex_df = sims_df[["model_type","cos_sim_0.01_mean","cos_hun_mean","cos_sim_0.01_std","cos_hun_std"]].copy()

#  latex_df = latex_df.drop(columns=["pred_oos_prob_mean","pred_oos_prob_std","pearson_r_oos_mean","pearson_r_oos_std"])
for metric in ["cos_sim_0.01","cos_hun"]:
    def fmt_func(row):
        mean_score = row[f"{metric}_mean"]
        std_score = row[f"{metric}_std"]
        if np.isnan(mean_score) or np.isnan(std_score):
            fmt_str = "-"
        else:
            fmt_str = f"${mean_score:.3f} \pm {std_score:.3f}$"
        return fmt_str
    latex_df[metric] = latex_df.apply(fmt_func, axis=1) 
    latex_df = latex_df.drop(columns=[f"{metric}_mean",f"{metric}_std"])
latex_df.loc[:,"model_type"] = latex_df["model_type"].replace(model_type_to_name)
# rename columns
latex_df.columns = ["Model",r"$\mathbb{C}_\text{BIN} \Uparrow$",r"$\mathbb{C}_\text{HUN} \Uparrow$"]
# latex_table = latex_df.to_latex(index=False, escape=False)

In [8]:
display(latex_df)

,Model,$\mathbb{C}_\text{BIN} \Uparrow$,$\mathbb{C}_\text{HUN} \Uparrow$
0,FraGNNet-D3 (+Edges),$0.716 \pm 0.001$,$0.687 \pm 0.001$
1,FraGNNet-D3 (-CE),$0.711 \pm 0.001$,$0.683 \pm 0.001$
2,FraGNNet-D4 (-CE),$0.721 \pm 0.001$,$0.694 \pm 0.001$